# Generated by Django 5.1 on 2024-08-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=300, null=True)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book_desciption', models.TextField()),
                ('sku', models.CharField(max_length=13, unique=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('book_slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
